# Generated by Django 3.1 on 2020-09-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftlist',
            name='status',
            field=models.CharField(choices=[('purchased', 'Purchased'), ('notpurchased', 'Not Purchased')], default='notpurchased', max_length=20),
        ),
    ]
