# Generated by Django 3.1 on 2020-09-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_auto_20200929_2101'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='giftlist',
            constraint=models.UniqueConstraint(fields=('user', 'gift'), name='unique_user_gift_list'),
        ),
    ]
