# Generated by Django 3.1 on 2020-10-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0005_auto_20201001_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='gift',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='gifts.gift'),
        ),
    ]
