# Generated by Django 3.1 on 2020-10-01 21:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0006_auto_20201001_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0)]),
        ),
    ]
